version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hotel_cmr
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: hotel_cmr
      DB_HOST: db
